id: 0591fcfd83b64569bfd40bb1bc6ba358
initial_creation_type: ocr
source_metadata:
  volumes:
    e2420a5925c149879af5dbd5d9060e3c:
      base_file: v019.txt
      image_group_id: I1PD95864
      title: རིམ་པ་ལྔ་པའི་དཀའ་འགྲེལ།
      total_pages: 1418
      volume_number: 19
